### ISSUE TITLE
Issue with Multi-Line User Input Handling in Convo Class

### ISSUE THREAD

**Issue by justojavier00** [ai-folks/saola#5]
There seems to be an issue within the Interface class at `/home/justo/saola-private/src/saola/convo.py`, where user input that includes multiple line breaks—especially if copied from another source and pasted—results in the Convo object interpreting these as several inputs, some of which have empty content.

**Comment by wircho** [comment]
The shell UI still does not support multiline input, but we can close as this is now possible in the notebook UI
